[patch.crates-io.std_msgs]
path = "vendor/std_msgs/share/std_msgs/rust"

[patch.crates-io.action_msgs]
path = "vendor/action_msgs/share/action_msgs/rust"

[patch.crates-io.service_msgs]
path = "vendor/service_msgs/share/service_msgs/rust"

[patch.crates-io.unique_identifier_msgs]
path = "vendor/unique_identifier_msgs/share/unique_identifier_msgs/rust"

[patch.crates-io.builtin_interfaces]
path = "vendor/builtin_interfaces/share/builtin_interfaces/rust"

[patch.crates-io.rosidl_runtime_rs]
path = "vendor/rosidl_runtime_rs/share/rosidl_runtime_rs/rust"
